### PR TITLE
Aryanmajeed/issue21

### LINKED ISSUE #21: Create the post page component.
**Is your feature request related to a problem? Please describe.**
N/A

**Describe how the solution should behave**
The use should be able to see a post and it should be responsive. Also, allow the user to add a comment.

**Screenshots of the design/if any**
image

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by aryankarim**
## What?
Created the design for a single post page.
## Why?
With a bunch of dummy data now we can see how the page looks.
## How to use?
Go to this route: `http://localhost:3000/posts/anything` or this `http://localhost:3000/ar/posts/anything` for the Arabic version
## Screenshots 
screencapture-localhost-3000-posts-something-2021-10-14-23_07_34

### CODE REVIEW

**Review by HaiderAltufaily — APPROVED** [review]
LGTM, Nice work!

**Review by MuhannedNoman — APPROVED** [review]
The preview didn't work for me, so I am not sure about the design and responsiveness. But code LGTM feel free to merge if the design is fine.

**Review by EsraaY21 — APPROVED** [review]
LGTM

**Comment by HaiderAltufaily** [comment]
@aryanmajeed  One thing before merging: @EsraaY21 already made a page for the project details named `/projects/[projectId]` in #31, So make sure to pull and change the name of the page to prevent the conflicts

**Comment by aryankarim** [comment]
Thank you @HaiderAltufaily I will fix that right now.

**Comment by aryankarim** [comment]
@MuhannedNoman  Sometimes you have to delete the `.next` folder to clear out the cache. I don't know if that is the case with yours.

**Pull request merged**
